package com.eva.recorderapp.voice_recorder.domain.categories.models

enum class CategoryColor {
	COLOR_RED,
	COLOR_ORANGE,
	COLOR_YELLOW,
	COLOR_AMBER,
	COLOR_LIME,
	COLOR_GREEN,
	COLOR_EMERALD,
	COLOR_TEAL,
	COLOR_CYAN,
	COLOR_SKY,
	COLOR_BLUE,
	COLOR_INDIGO,
	COLOR_VIOLET,
	COLOR_PURPLE,
	COLOR_PINK,
	COLOR_ROSE,
	COLOR_UNKNOWN,
}